
// import Foot from "@/components/Foot";
// import Header from "@/components/Header";
import Script from "next/script";
import './globals.css';
import { ClerkProvider } from "@clerk/nextjs";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className="bg-slate-950 text-gray-200">
        {/* <Header /> */}
        <main className="container m-auto min-h-screen  pt-12">{children}</main>
        {/* <Foot /> */}
        <Script src="../node_modules/flowbite/dist/flowbite.min.js"></Script>
      </body>
    </html>
    </ClerkProvider>
  );
}

